parameters:
- name: RunUnitTestsOnWindows
  displayName: Run unit tests on Windows
  type: boolean
  default: true
- name: RunFunctionalTestsOnWindows
  displayName: Run functional tests on Windows
  type: boolean
  default: true
- name: RunUnitTestsOnLinux
  displayName: Run unit tests on Linux
  type: boolean
  default: false
- name: RunFunctionalTestsOnLinux
  displayName: Run functional tests on Linux
  type: boolean
  default: false
- name: RunUnitTestsOnMacOS
  displayName: Run unit tests on MacOS
  type: boolean
  default: false
- name: RunFunctionalTestsOnMacOS
  displayName: Run functional tests on MacOS
  type: boolean
  default: false

variables:
  BuildPlatform: Any CPU
  BuildConfiguration: Debug
  DOTNET_NOLOGO: 1
  NUGET_EXPERIMENTAL_CHAIN_BUILD_RETRY_POLICY: 3,1000
  SkipSigning: true
  CI: true

jobs:
- ${{ if eq(parameters.RunUnitTestsOnWindows, true) }}:
  - template: pull_request.job.yml
    parameters:
      name: UnitTestsWindows
      displayName: Unit Tests on Windows
      osName: Windows
      vmImage: windows-latest
      testType: Unit

- ${{ if eq(parameters.RunFunctionalTestsOnWindows, true) }}:
  - template: pull_request.job.yml
    parameters:
      name: FunctionalTestsWindows
      displayName: Functional Tests on Windows
      osName: Windows
      vmImage: windows-latest
      testType: Functional
      timeoutInMinutes: 180

- ${{ if eq(parameters.RunUnitTestsOnLinux, true) }}:
  - template: pull_request.job.yml
    parameters:
      name: UnitTestsLinux
      displayName: Unit Tests on Linux
      osName: Linux
      vmImage: ubuntu-latest
      testType: Unit

- ${{ if eq(parameters.RunFunctionalTestsOnLinux, true) }}:
  - template: pull_request.job.yml
    parameters:
      name: FunctionalTestsLinux
      displayName: Functional Tests on Linux
      osName: Linux
      vmImage: ubuntu-latest
      testType: Functional

- ${{ if eq(parameters.RunUnitTestsOnMacOS, true) }}:
  - template: pull_request.job.yml
    parameters:
      name: UnitTestsMac
      displayName: Unit Tests on MacOS
      osName: MacOS
      vmImage: macos-latest
      testType: Unit

- ${{ if eq(parameters.RunFunctionalTestsOnMacOS, true) }}:
  - template: pull_request.job.yml
    parameters:
      name: FunctionalTestsMac
      displayName: Functional Tests on MacOS
      osName: MacOS
      vmImage: macos-latest
      testType: Functional
